spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect   

  h2:
    console.enabled: true 

server:
  port: 9003 

logging:
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: c:/tmp/application.log
  level:
   root: ERROR
   '[org.springframework]': ERROR
   '[org.hibernate]': ERROR
   '[org.apache]' : ERROR
   '[com.infogain.assessment]' : INFO 
  